# Generated by Django 6.0 on 2026-04-21 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample_app', '0005_information'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
    ]
